---
- name: Configure pgpool VM
  hosts: pgpool
  become: yes
  vars_files:
    - /group_vars/all.yml

  tasks:
    - name: Update packages and install required packages
      apt:
        name:
          - pgpool2
        update_cache: yes
        state: present

    - name: Set up pool_passwd file
      copy:
        content: "nagios:quizztine"
        dest: /etc/pgpool2/pool_passwd
        owner: root
        group: pgpool
        mode: '0640'

    - name: Copy and render pgpool.conf template
      ansible.builtin.template:
        src: pgpool.conf.j2
        dest: /etc/pgpool2/pgpool.conf
        owner: root
        group: pgpool
        mode: '0640'

    - name: Configure pool_hba.conf
      blockinfile:
        path: /etc/pgpool2/pool_hba.conf
        block: |
          host    all         all         {{ flask_ip }}/32          trust
        owner: root
        group: pgpool
        mode: '0640'

    - name: Enable and start pgpool2 service
      systemd:
        name: pgpool2
        enabled: yes
        state: restarted
