---
- name: Configure PostgreSQL Master
  hosts: postgres-master
  become: yes
  tasks:
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present

    # Add further tasks for configuring PostgreSQL
